name: Update Free Nodes


on:

  workflow_dispatch:

  schedule:

    - cron: "0 */6 * * *"



jobs:

  update:

    runs-on: ubuntu-latest


    permissions:

      contents: write



    steps:


    - name: Checkout

      uses: actions/checkout@v4

      with:

        fetch-depth: 0



    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: Install Python

      run: |

        pip install requests pyyaml



    - name: Fetch Nodes

      run: |

        mkdir -p output

        python scripts/fetch_nodes.py



    - name: Clean Nodes

      run: |

        python scripts/clean_nodes.py



    - name: Check Result

      run: |

        echo "最终节点数量"

        wc -l output/nodes.txt



    - name: Commit

      uses: stefanzweifel/git-auto-commit-action@v5

      with:

        commit_message: "自动更新节点"

        file_pattern: |

          output/nodes.txt

        push_options: --force
