name: Update Free Nodes


on:

  workflow_dispatch:

  schedule:

    - cron: "0 */6 * * *"



jobs:


  update:


    runs-on: ubuntu-latest


    permissions:

      contents: write



    steps:


    - name: Checkout

      uses: actions/checkout@v4

      with:

        fetch-depth: 0



    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: Install dependencies

      run: |

        pip install requests



    - name: Clean Nodes

      run: |

        python scripts/clean_nodes.py



    - name: Commit and push

      run: |

        git config --global user.name "github-actions[bot]"

        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"


        git pull --rebase origin main


        git add output/nodes.txt


        git commit -m "自动更新节点" || exit 0


        git push origin main
