name: Update Free Nodes


on:

  workflow_dispatch:

  schedule:

    - cron: "0 */6 * * *"



jobs:


  update:


    runs-on: ubuntu-latest



    permissions:

      contents: write



    steps:


    - name: Checkout

      uses: actions/checkout@v4

      with:

        fetch-depth: 0



    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: Install

      run: |

        pip install requests



    - name: Clean Nodes

      run: |

        python scripts/clean_nodes.py



    - name: Commit Nodes


      uses: stefanzweifel/git-auto-commit-action@v6


      with:

        commit_message:

          "Auto update nodes"


        file_pattern:

          output/nodes.txt


        push_options:

          --force
